name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'maven'
      - name: build docs
        run: |
          mvn generate-sources
          mvn javadoc:javadoc
      - name: deploy docs
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/docs/apidocs